ELF=example.elf

SRC=example.c startup.S vectors.S
MCU=atmega328p

CC		=	avr-gcc
LD		=	avr-gcc
AS		=	avr-gcc
SIZE	=	avr-size
RUN		=	avr-run
STRIP	=	avr-strip

LDFLAGS	=	-nostdlib

include ./Makefile.in
