ELF=timer_a.elf

SRC=timer_a.c
MCU=msp430g2553

CC		=	msp430-elf-gcc
LD		=	msp430-elf-gcc
AS		=	msp430-elf-gcc
SIZE	=	msp430-elf-size
RUN		=	msp430-elf-run
STRIP	=	msp430-elf-strip

include ../Makefile.in

# vim:set ts=4 tw=79 syntax=make et:
